### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by martinloesethjensen** [martinloesethjensen/watched_app#1]
Handle movie search with The Movie DB api request: `GET /search/movie`

## TODOs: 

- [x] #12
- [x] Search screen UI
  - [x] Text field --> trigger on change and handle with rxjava debounce on endpoint request in the viewmodel
  - [x] List of results as either tiles or cards (Would prefer cards that have loaded image poster)
- [x] Search viewmodel to handle ui state and called search api service
