### ISSUE TITLE
Movie details screen

### ISSUE THREAD

**Issue by martinloesethjensen** [martinloesethjensen/watched_app#21]
As a user I would like to see the details of a movie.

## TODOs

- [ ] movie details screen, ViewModel, and UI state
- [ ] Get movie by id usecase
- [ ] Get movie by id from watchlist dao
